### ISSUE TITLE
Server Side Rendering (initialNavigation: 'enabledBlocking') seems to stop the module from working

### ISSUE THREAD

**Issue by Haves1001** [penleychan/ngx-transloco-router#10]
Following the README, I have integrated this ngx-transloco-router and everything seems to work fine when it comes to remembering the selected language (via a lang picker).
What seems not to be working is adding the language to the current path, I'm not sure if this might be an Angular 15 problem or if the package does not work with SSR? As soon as I remove `initialNavigation: 'enabledBlocking',` the package is working fine.

My AppRoutingModule looks like this and I'm importing the TranslocoRootModule in my AppModule:
```
@NgModule({
  imports: [
    RouterModule.forRoot(routes, {
      initialNavigation: 'enabledBlocking',
      scrollPositionRestoration: 'enabled',
      anchorScrolling: 'enabled',

    }),
    LocalizeRouterModule.forRoot(routes)
  ],
  exports: [RouterModule, LocalizeRouterModule],
  providers: [
    {
      provide: LOCALIZE_ROUTER_CONFIG,
      useValue: localizeRouterConfig({
        translateRoute: true,
      })
    }
  ]
})
export class AppRoutingModule { }
```

**Comment by penleychan** [comment]
Hello, the implementation is pretty much the same as the ported library. You need to enable initial navigation as per their documentation https://github.com/gilsdav/ngx-translate-router#deal-with-initialnavigation

**Comment by Haves1001** [comment]
It seems to me that ngx-transloco-router expects only one argument (the routes) for `forRoot()`, also visible in the localize-router.module.d.ts:

`static forRoot(routes: Routes): ModuleWithProviders<LocalizeRouterModule>;`

As a result the compiler is  complaining that `Expected 1 arguments, but got 2`.

**Comment by penleychan** [comment]
Remove: initialNavigation: 'enabledBlocking', from your RouterModule

Your provider should look like this:
````
{
      provide: LOCALIZE_ROUTER_CONFIG,
      useValue: localizeRouterConfig({
        translateRoute: true,
        initialNavigation: true
      })
}
````

**Comment by Haves1001** [comment]
Ah I see, so a bit different from how ngx does it. Thank you for pointing this out :)
When following your snippet (and removing `initialNavigation` from `RouterModule.forRoot`) I get the following error:
```
ERROR TypeError: Cannot read properties of undefined (reading 'afterPreactivation')
    at /Volumes/source/<project-dist-dir>/server/vendor.js:198738:54
    ....
```

**Comment by penleychan** [comment]
Seems like there's actually a lot of changes under Angular's 15 (around 15.0.3 and onwards) routing due to refactoring.
I've published [15.0.0-beta.1](https://www.npmjs.com/package/@penleychan/ngx-transloco-router/v/15.0.0-beta.1) which should hopefully fixes those issues. 

I'm not entirely sure how many users are using this library. This project started for a specific client requirement that was already using transloco and no plan to update from angular 13. So I am relying on you/community to test it out, I've only tested in my demo app and bare min setup for SSR.

Once you confirm it's working i'll publish a release.

**Comment by Haves1001** [comment]
Thank you for the quick response and cutting a new beta release! :) 
I'm unfortunately not able to use this release in my project, as it seems that the index.d.ts is missing in the library: `Cannot find module '@penleychan/ngx-transloco-router' or its corresponding type declarations`

Despite from that it seems that you already have a good audience for this library, given that I can see on npm roughly 100 weekly downloads. But I'm of course not in your shoes when it comes to maintaining this, it has been THE missing feature for me in transloco though.

**Comment by penleychan** [comment]
Sorry about that, mistake on my end. Could you try [15.0.0-beta.3](https://www.npmjs.com/package/@penleychan/ngx-transloco-router/v/15.0.0-beta.3)

Unfortunately majority of the downloads skewed due to bots scrapping npmjs. Anyways thanks for using this library.

**Comment by Haves1001** [comment]
Yeah I see, npm stats might be tainted and I guess CI/CD pipelines can add more to it.

The latest version that you cut seems to work with Angular 15 without errors, I only see this warning in the console when I load a page: 
```
DEPRECATED: DI is instantiating a token "LocalizedRouter" that inherits its @Injectable decorator but does not provide one itself.
This will become an error in a future version of Angular. Please add @Injectable() to the "LocalizedRouter" class.
```

What I still see though - and I'm not 100% sure if that is the exptected behavior - is that the website flickers from the default language (English) to the selected different language on a refresh. I can also see that the HTML that is generated by SSR contains all the strings in English and the translation is only happening on the javascript client side in the browser.

**Comment by penleychan** [comment]
Thanks for that error message.

Flickering issue is caused by SSR not able to determine the value of the default lang on first render. Default cache mechanism is Localstorage and server side apps don't have "localstorage". So, to get around for example in NodeJS server side with express is you would use cookies, and you can change the cache mechanism to "Cookie". So this is really depends on your implementation. See [ngx-translate-router#server-side](https://github.com/gilsdav/ngx-translate-router#server-side).

**Comment by Haves1001** [comment]
Isn't that just the case if I call <hostname> without a path? 

I should have added that I'm already calling <hostname>/it/<rest of path> (or any other language) so that the language does not need to be determined by the browser environment. While the app is (rightfully) ignoring my browser language on client side and is switching (with flickering) from the default language English to any other language, the same thing does not seem to work on the server side.
I can see though that the server is requesting the relevant local from the given transloco resource and is also packaging it in case I add it to the TransferState - just the html is not translated to the given target language.

**Comment by penleychan** [comment]
Can you give [15.0.0](https://www.npmjs.com/package/@penleychan/ngx-transloco-router/v/15.0.0) a try. I think I found the culprit with the SSR issue, tested it and it seems to be translated in the html source: 

![image](https://user-images.githubusercontent.com/5407937/210459981-a4968d74-1804-4d87-81d4-8b29fcb72873.png)

**Comment by Haves1001** [comment]
Tried out 15.0.0 and that seems to fix the issue. I also don't see the warning anymore.

Thanks a lot!
