### ISSUE TITLE
Deal with initialNavigation in SSR mode

### ISSUE THREAD

**Issue by pilomat** [penleychan/ngx-transloco-router#12]
Hi,

I'm trying to follow this [guide](https://github.com/gilsdav/ngx-translate-router/tree/master#deal-with-initialNavigation) to enable  initialNavigation in the Universal project.

It looks like something is not working properly, as soon as I start up the application (it is enough to use `ng serve` to reproduce the issue) the page is not rendering correclty. A black page is diplayed.

Please refer to this [project](https://github.com/pilomat/angular-ssr-transloco-router) to reproduce the issue.

Thanks in advance

**Comment by penleychan** [comment]
For now remove `initialNavigation` from `localizeRouterConfig`, I will need to investigate as this is a new bug introduced in angular 15 router.

**Comment by pilomat** [comment]
Thanks! Could be similar to this [issue](https://github.com/gilsdav/ngx-translate-router/issues/141) ?

**Comment by penleychan** [comment]
Thanks, I've made the change and updated the package to 15.0.1. This commit https://github.com/penleychan/ngx-transloco-router/commit/61eea21f40b22c3f0eb360becd63cb63c8796287 should fix the issue.
