### ISSUE TITLE
DefaultLangFuction is not working properly

### ISSUE THREAD

**Issue by pilomat** [penleychan/ngx-transloco-router#13]
I'm trying to override the defaultLang but it looks like is not working. 

`
 provide: LOCALIZE_ROUTER_CONFIG,
      useValue: localizeRouterConfig({
        defaultLangFunction: () => 'fr'
      }),
`
Application always return /en. 

Please refer to this [project](https://github.com/pilomat/angular-ssr-transloco-router/tree/default_lang-issue) for more information.

PS. I've already tried to use this [workaround](https://github.com/penleychan/ngx-transloco-router/issues/6) but it's not working.

**Comment by penleychan** [comment]
Hello, it is working as intended the purpose of that function is for a redirect to /{lang} if there no lang in the URL detected. So for example if you navigate to http://localhost:4200/ it should redirect you to '/fr' rather than '/en' default that was defined in TRANSLOCO_CONFIG. Make sense?

**Comment by pilomat** [comment]
Make same :-). Something was wrong with my brower cache. 

Thanks!
