### ISSUE TITLE
defaultLangFunction

### ISSUE THREAD

**Issue by e404r** [penleychan/ngx-transloco-router#6]
defaultLangFunction not working

**Comment by e404r** [comment]
Always returns  /en

**Comment by e404r** [comment]
alwaysSetPrefix: true
cacheMechanism: "LocalStorage"
cacheName: "app_lang"
cookieFormat: "{{value}};{{expires}}"
defaultLangFunction: undefined
escapePrefix: "!"
initialNavigation: false
prefix: "ROUTES."
translateRoute: true
useCachedLang: true

**Comment by penleychan** [comment]
Can you provide more details regarding to your setup? Specifically this portion of the code
```
providers: [
  {
    provide: LOCALIZE_ROUTER_CONFIG,
    useValue: localizeRouterConfig({
      ...
    })
  }
]
```
I would assume you overriding some the defaults. You don't necessary need to provide everything just what you want to override.
So for example in your case only differences between yours and the default value is `translateRoute` and `cacheName`, so you would just do this:
```
useValue: localizeRouterConfig({
     cacheName: "app_lang",
     translateRoute: true
})
```

**Comment by e404r** [comment]
I adjusted it myself

```
const lng = localStorage.getItem('app_lang');
if (!lng) {  var mylng='fr'; }else{ var mylng=lng;}

providers: [{
      provide: LOCALIZE_ROUTER_CONFIG,
      useValue: localizeRouterConfig({
        translateRoute: true,
        cacheName:'app_lang',
        defaultLangFunction: () =>  `${mylng}`,
        /
      }),}]
```


thanks

**Comment by penleychan** [comment]
Hi,

I am unable to reciprocate the issue. Seems working as intended.

`defaultLangFunction` function is triggered whenever there is no locale detected on your URL. 
For example if you navigate to `https://localhost:4200` the function will trigger and redirects to `https://localhost:4200/fr`

**Comment by e404r** [comment]
When I did not set this setting, The site was automatically redirected site.com/en
By default I set  in transloco-root.module.ts          defaultLang: 'fr',   But it didn't work

After adding the code  
const lng = localStorage.getItem('app_lang');
if (!lng) {  var mylng='fr'; }else{ var mylng=lng;}
defaultLangFunction: () =>  `${mylng}`,
Works perfectly
thanks

**Comment by e404r** [comment]
thanks

**Comment by penleychan** [comment]
Ah okay I see what you mean. It doesn't account for transloco's default value. Easy fix. I'll fix that and update to angular 14 sometimes today or sometimes today.
