### ISSUE TITLE
angular ssr LocalizeRouterModule.forRoot(routes),

### ISSUE THREAD

**Issue by e404r** [penleychan/ngx-transloco-router#7]
after add     LocalizeRouterModule.forRoot(routes),   angular ssr not working.  error not show, only page reloadid infinty

**Comment by e404r** [comment]
for example add  this function   LocalizeRouterModule.forRoot(routes, {
    ...
    initialNavigation: true
  })

**Comment by penleychan** [comment]
Have you looked into https://github.com/gilsdav/ngx-translate-router#server-side on how it implement SSR? Since this library is a direct port implementation should be quite identical.

**Comment by e404r** [comment]
> 

I looked at the documentation.  But it still doesn't work :(

**Comment by penleychan** [comment]
I just tested with a barebone SSR starter template I found on github. Seems to be working fine.
View Source URL:
![image](https://user-images.githubusercontent.com/5407937/183674417-c4479807-e7df-4ee6-8752-2c289a4b2e43.png)

View Source's contents:
![image](https://user-images.githubusercontent.com/5407937/183674618-5c279053-8ef6-4833-95ea-858d81d240f4.png)

**Comment by e404r** [comment]
Now I saw the server logs and I was using the Jq library, which was giving me an error, Thanks for your help and have a great day👌🙈    🙌

**Comment by e404r** [comment]
Damn, I thought it was fixed, "dev:ssr": "ng run angular-starter:serve-ssr",  works fine.  

But  "build:ssr" &  "serve:ssr":   still the same mistake👽   Can you share your code?

**Comment by penleychan** [comment]
https://github.com/penleychan/angular-ssr-transloco-router

**Comment by e404r** [comment]
thank you

**Comment by e404r** [comment]
It doesn't work either, check it out
https://mega.nz/embed/lHx2BKCS#in_wyp7oOPFeyIUshROFxPqBAzNZsZ2D2CvfX4GXzho

**Comment by penleychan** [comment]
Sorry, I didn't run serve:ssr. The ` baseUrl` on the environment file port need to match with node express port 4000. After changing the port build and serve. App should be running

**Comment by e404r** [comment]
I have tried this from the beginning but still no success  :(

**Comment by e404r** [comment]
I do not believe 🎆  ` fallbackLang` It was corrected after the addition 😱  

- [*] fallbackLang

**Comment by penleychan** [comment]
Awesome, glad you got everything sorted out.
