### ISSUE TITLE
Update  @angular/router@"^14.2.8" for Angular 15

### ISSUE THREAD

**Issue by Haves1001** [penleychan/ngx-transloco-router#9]
It seems that this library is currently bound to Angular 14. Are you planning to make it compatible with Angular 15 as well?
```
npm i @penleychan/ngx-transloco-router
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: project@0.0.0
npm ERR! Found: @angular/router@15.0.1
npm ERR! node_modules/@angular/router
npm ERR!   @angular/router@"^15.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/router@"14.2.8" from @penleychan/ngx-transloco-router@14.0.0
npm ERR! node_modules/@penleychan/ngx-transloco-router
npm ERR!   @penleychan/ngx-transloco-router@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by penleychan** [comment]
Doesn't seem to be any breaking changes in terms of angular/router in 15. 
I've just updated the package peer dependencies to include ` "@angular/router": ">=14.0.0"`

Could you try updating/using version 14.0.2

**Comment by penleychan** [comment]
Closing this ticket, commit cf414fcdd31063b4b373216374d2a7a41470c13c should be sufficient enough to resolve this issue.

**Comment by Haves1001** [comment]
Sorry for the late reply. I tried it out today and the installation is indeed working now. Thanks you for the quick fix!

It seems though that the default Angular app setup now comes with rxjs 7.5.7 and ngx-transloco-router requires 6.6.7. 
When downgrading to 6.6.7 I get this error when building the project:

> ./node_modules/@penleychan/ngx-transloco-router/fesm2020/penleychan-ngx-transloco-router.mjs:154:11-25 - Error: export 'firstValueFrom' (imported as 'firstValueFrom') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrame, animationFrameScheduler, asap, asapScheduler, async, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queue, queueScheduler, race, range, scheduled, throwError, timer, using, zip)

**Comment by penleychan** [comment]
Thanks for reporting that, no idea why it was adding rxjs@6.6.7 during build as peer dependencies. Cleared all my caches and lock files seems to fixes it on build. v14.0.3 should no longer requires any rxjs dependencies. 

I did noticed there is a breaking change on angular 15 router due to new API introducing standalone. I will take a look into that whenever I have spare time. For now standalone component routing is not supported.
